name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted # Runs on your self-hosted runner

    strategy:
      matrix:
        node-version: [18.x] # Specify the Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # Specify your Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.PROD }}" >> .env  # Corrected to use the correct syntax for accessing secrets
      - name: create .env.test file
        run: |
          touch .env.test
          echo "${{ secrets.TEST_URLS }}" >> .env.test  # Corrected to use the correct syntax for accessing secrets

      - name: Run tests
        run: npm test

  build:
    runs-on: self-hosted
    needs: test # This job will run only after the test job is successful

    strategy:
      matrix:
        node-version: [18.x] # Specify the Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the project
        run: npm run build --if-present
